theme: minima
title: My first GitHub Pages Blog
author: Mwaka Daniel
description: This is just a basic blog. I am learning how to write blogs and publish on the GitHub Pages platform. In the future I will be writing on Data Science related topics
